sudo: required
services:
  - docker

before_install:
  - docker build -t GiovannaPh777/docker-react -f Dockerfile.dev .

script:
  - docker run GiovannaPh777/docker-react npm run test -- --coverage


